### ISSUE TITLE
object has no attribute 'has_multiscale_discrs'

### ISSUE THREAD

**Issue by Ted-developer** [lucidrains/magvit2-pytorch#22]
Thank you very much for your work. I've encountered an issue while using multiple GPUs with accelerate to launch:

Error message as follows:

magvit2-pytorch/magvit2_pytorch/trainer.py", line 203, in __init__
    raise AttributeError("'{}' object has no attribute '{}'".format(
    self.has_multiscale_discrs = self.model.has_multiscale_discrs
  File "magvit2-pytorch/magvit2_pytorch/.magvit2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
AttributeError    : self.has_multiscale_discrs = self.model.has_multiscale_discrs'DistributedDataParallel' object has no attribute 'has_multiscale_discrs'

How should I resolve this? Thank you.

**Comment by Du-Yao** [comment]
I'm sure that the reason is the model is wrapped by Accelerate. You can use _self.model.module.has_multiscale_discrs_ or _self.unwrapped_model.has_multiscale_discrs_ to solve this issue. And I also find many bugs on multi-GPUs training and validation, and I'm fix these issues. If I successfully run the code for multiple GPUs, and the author does not mind, I will share these codes with the author. @lucidrains

**Comment by lucidrains** [comment]
@Ted-developer thanks for raising this issue

it is a quirk with accelerate library and it being wrapped with DDP, as Du Yao noted. i put in a fix for all the places where i think there should be unwrapping @Du-Yao def welcome a PR from you if you spot any others missing!
